/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package samples.quickstart.service.adb.xsd;

public class linboxfunctions {
  public static boolean det(SWIGTYPE_p_std__istream matrix_in, SWIGTYPE_p_std__ostream det_out) {
    return linboxfunctionsJNI.det(SWIGTYPE_p_std__istream.getCPtr(matrix_in), SWIGTYPE_p_std__ostream.getCPtr(det_out));
  }

  public static String detFiles(String mat) {
    return linboxfunctionsJNI.detFiles(mat);
  }

  public static boolean rank(SWIGTYPE_p_std__istream matrix_in, SWIGTYPE_p_std__ostream rank_out) {
    return linboxfunctionsJNI.rank(SWIGTYPE_p_std__istream.getCPtr(matrix_in), SWIGTYPE_p_std__ostream.getCPtr(rank_out));
  }

  public static String rankFiles(String mat) {
    return linboxfunctionsJNI.rankFiles(mat);
  }

  public static int estimateRankTime(String matfile) {
    return linboxfunctionsJNI.estimateRankTime(matfile);
  }

  public static boolean val(SWIGTYPE_p_std__istream matrix_in, SWIGTYPE_p_std__ostream trace_out) {
    return linboxfunctionsJNI.val(SWIGTYPE_p_std__istream.getCPtr(matrix_in), SWIGTYPE_p_std__ostream.getCPtr(trace_out));
  }

  public static String valFiles(String mat) {
    return linboxfunctionsJNI.valFiles(mat);
  }

  public static boolean trace(SWIGTYPE_p_std__istream matrix_in, SWIGTYPE_p_std__ostream trace_out) {
    return linboxfunctionsJNI.trace(SWIGTYPE_p_std__istream.getCPtr(matrix_in), SWIGTYPE_p_std__ostream.getCPtr(trace_out));
  }

  public static String traceFiles(String mat) {
    return linboxfunctionsJNI.traceFiles(mat);
  }

  public static boolean smithNormalForm(SWIGTYPE_p_std__istream matrix_in, SWIGTYPE_p_std__ostream snf_out) {
    return linboxfunctionsJNI.smithNormalForm(SWIGTYPE_p_std__istream.getCPtr(matrix_in), SWIGTYPE_p_std__ostream.getCPtr(snf_out));
  }

  public static String smithNormalFormFiles(String mat) {
    return linboxfunctionsJNI.smithNormalFormFiles(mat);
  }

}
