OBJ=givintcstor.C      givintfactor.inl      givintnumtheo.C      givintrns.h      givintsub.C givcompgmp.h      givintdiv.C           givintgcd.C            givintnumtheo.h        givintrns_convert.inl giverror.C             givinteger.C           givintio.C             givintnumtheo.inl      givintrns_cstor.inl giverror.h             givinteger.h           givintmisc.C           givintpow.C            givintrsa.C givintadd.C            givinteger.inl         givintmod.C            givintprime.C          givintrsa.h givintcompare.C        givintfactor.h         givintmul.C            givintprime.h          givintrsa.inl

SUBDIRS=

include Makefile.rules
