#OBJ=lin_dom_thunk_b_b.h lin_dom_thunk_symmetric.inl lin_dom_thunk_nonsquare.inl lin_dom_thunk_symmetrize.inl lin_dom_thunk_sequence.inl lin_dom_thunk_square.inl
OBJ=lin_dom_thunk_square.h
SUBDIRS=

include Makefile.rules
