/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.27
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package samples.quickstart.service.adb.xsd;

class linboxfunctionsJNI {
  public final static native boolean det(long jarg1, long jarg2);
  public final static native long detFiles(String jarg1);
  public final static native boolean rank(long jarg1, long jarg2);
  public final static native int rankFiles(String jarg1);
  public final static native boolean val(long jarg1, long jarg2);
  public final static native int valFiles(String jarg1);
  public final static native boolean trace(long jarg1, long jarg2);
  public final static native int traceFiles(String jarg1);
}
